title: "Predicción de GHI con BiLSTM"
author: "Isabella Velasco · Emergente"
logo: ""

execute:
  execute_notebooks: "off"

html:
  use_multitoc_numbering: false

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath

sphinx:
  extra_extensions:
    - sphinx_togglebutton
    - sphinx_copybutton
  config:
    html_theme: "sphinx_book_theme"
    html_theme_options:
      pygments_dark_style: "monokai"
      show_navbar_depth: 2
      use_download_button: true
      repository_url: "https://github.com/isvelascor1061/solar-forecast-emergente"
      use_repository_button: true
      home_page_in_toc: true
    html_context:
      default_mode: "dark"
    nb_execution_mode: "off"
    # Show toggle button for hide-input cells
    togglebutton_hint: "Ver código"
    togglebutton_hint_hide: "Ocultar código"
